import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/AuthProvider/SessionProvider";
// import DashboardLayout from "@/components/Layouts/DashboardLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Back Office Portal",
  description: "Generated by Back Office Portal",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-screen-grey`}>
        <SessionProvider session={session}>
          <Navbar isLoggedIn={true} />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
